services:
  java_app :
    container_name : java_app
    image : bga/java_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/task5db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=qwerty
    depends_on:
      - java_db

  java_db:
    container_name : java_db
    image : postgres:12
    ports:
      - 15432:5432
    environment:

      POSTGRES_PASSWORD : qwerty
      POSTGRES_USER : postgres
      POSTGRES_DB : task5db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: {}
